cabal-version: 3.0
name: llama-hs
version: 0.1.0.0
synopsis: The Llama Programming Language
description: Empowering everyone to build nonexistent software.
homepage: https://github.com/jawadcode/llama-hs.git
license: MIT
license-file: LICENSE
author: Jawad W. Ahmed
maintainer: jawad.w.ahmed@gmail.com
copyright: (c) 2025-2026 Jawad W. Ahmed
category: Compilers
build-type: Simple
extra-doc-files: CHANGELOG.md

source-repository head
  type:     git
  location: https://github.com/jawadcode/llama-hs.git

common common-properties
  ghc-options: -Wall
  other-extensions:
    ApplicativeDo
    OverloadedStrings

  build-depends:
    base >=4.20 && <4.23,
    bytestring ^>=0.12,

  default-language: GHC2024

common relude
  build-depends: relude ^>=1.2
  default-extensions: NoImplicitPrelude

library
  import: common-properties, relude
  hs-source-dirs: src
  exposed-modules:
    AST
    Lexer
    Lexer.Internal.Alex
    Lexer.Internal.Helpers
    Lexer.Token
    Utils.Range

  build-depends: array ^>=0.5
  build-tool-depends: alex:alex ^>=3.5

executable llama-hs
  import: common-properties, relude
  hs-source-dirs: app
  main-is: Main.hs
  build-depends: llama-hs
