cabal-version:      3.0
name:               llama-hs
version:            0.1.0.0
synopsis:           The Llama Programming Language
-- description:
homepage:           https://github.com/jawadcode/llama-hs.git
license:            MIT
license-file:       LICENSE
author:             Jawad W. Ahmed
maintainer:         jawad.w.ahmed@gmail.com
-- A copyright notice.
-- copyright:
category:           Compilers
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- Extra source files to be distributed with the package, such as examples, or a
-- tutorial module.
-- extra-source-files:

common common-properties
    ghc-options:        -Wall
    other-extensions:   ApplicativeDo, OverloadedStrings
    build-depends:
        base >= 4.20.2 && < 4.21,
        bytestring  >= 0.12.2 && < 0.13
    default-language:   GHC2024

common relude-auto
    build-depends:      relude  >= 1.2.2 && < 1.3
    mixins:
        base hiding (Prelude),
        relude (Relude as Prelude),
        relude

library utils
    import:             common-properties, relude-auto
    exposed-modules:    Utils.Range
    hs-source-dirs:     src-utils

library lexer
    import:             common-properties
    exposed-modules:    Lexer
    -- other-modules:
    -- build-depends:
    hs-source-dirs:     src-lexer
    build-depends:
        llama-hs:utils,
        array >= 0.5.8 && < 0.6
    build-tool-depends: alex:alex ^>= 3.5.4.2

executable llama-hs
    import:             common-properties, relude-auto
    main-is:            Main.hs
    other-modules:      AST
    build-depends:      llama-hs:lexer
    hs-source-dirs:     src
